#!/usr/bin/env bash
# Replace only the localhost
sudo sed -i '/127.0.0.1\s\+localhost/s/127.0.0.1/127.0.0.2/' ~/temp

# Add facebook.com entry if it doesn't already exist
if ! grep -q "8.8.8.8 facebook.com" ~/temp; then
  echo "8.8.8.8 facebook.com" | sudo tee -a ~/temp > /dev/null
fi
