#!/usr/bin/env bash
# Replace only the localhost
HOSTS_FILE="/etc/hosts"


cp $HOSTS_FILE ${HOSTS_FILE}.backup


sed -i '/localhost/d' $HOSTS_FILE
sed -i '/facebook.com/d' $HOSTS_FILE


echo "127.0.0.2 localhost" >> $HOSTS_FILE
echo "8.8.8.8 facebook.com" >> $HOSTS_FILE
