#!/usr/bin/env bash
# Replace only the localhost
HOSTS_FILE="/etc/hosts"


grep -v -E 'localhost|facebook.com' "$HOSTS_FILE" > /tmp/hosts.new


echo "127.0.0.2 localhost" >> /tmp/hosts.new
echo "8.8.8.8 facebook.com" >> /tmp/hosts.new


cat /tmp/hosts.new > "$HOSTS_FILE"


rm /tmp/hosts.new
